Repository DeveloperAcademy-POSTECH/2024-MacC-A05-Chillin, pull requests merged in 2024-12, with the labels that each got.

#411 [Chore] 애플 펜슬 더블 탭 제스처로 펜슬 <-> 지우개 스위치
  Presentation/MainPDF/ViewModel/MainPDFViewModel.swift
  Presentation/OriginalPaper/Menus/Drawing/DrawingView.swift
  Presentation/OriginalPaper/OriginalViewController.swift
Labels: Chore

#416 [Chore] HomeView & editFigure 아이콘 크기 변경
  Presentation/Home/HomeView.swift
  Presentation/OriginalPaper/Menus/FigureList/Figure/FigureMenu.swift
  Resources/PDFs/Reazy Sample Paper.pdf
Labels: Chore, PR-NeedReview

#418 [Fix] 코멘트 밑줄 커스텀 수정
  Presentation/OriginalPaper/Menus/Comment/ViewModel/CommentViewModel.swift
Labels: Fix

#417 [Release] 버전 업데이트
  Reazy.xcodeproj/project.pbxproj
Labels: Release
