Repository DeveloperAcademy-POSTECH/2024-MacC-A05-Chillin, pull requests merged in 2025-04, with the labels that each got.

#480 [Feat] 4.0 HomeView Design 반영
  DesignSystem/Views/CustomAlert.swift
  Domain/Entities/PaperInfo.swift
  Domain/Entities/Tag.swift
  Domain/Interfaces/DynamicCell.swift
  Domain/UseCases/TagViewUseCase.swift
  Presentation/Home/HomeFolderPopoverView.swift
  Presentation/Home/HomeListView.swift
  Presentation/Home/HomeSearch/Cell/HomePDFCell.swift
  Presentation/Home/HomeSearch/Cell/PDFTagCell.swift
  Presentation/Home/HomeSearch/HomeSearchView.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/MoveFolderView.swift
  Presentation/Home/Paper/PaperListCell.swift
  Presentation/Home/PaperListView.swift
  Presentation/Home/SearchWordView.swift
  Presentation/Home/TagControl/TagControlView.swift
  Presentation/Home/TagSearch/TagView.swift
  Presentation/Home/TagSearch/TagViewModel.swift
  Presentation/Home/ViewModel/HomeViewModel.swift
  Presentation/MainPDF/MainPDFView.swift
  Presentation/MainPDF/PDFInfoMenu.swift
  Reazy.xcodeproj/project.pbxproj
Labels: Feature, PR-NeedReview

#492 [Fix] 코멘트 및 태그 뷰 부분 수정
  DesignSystem/Views/CustomAlert.swift
  Domain/Entities/Tag.swift
  Presentation/Home/HomeSearch/Cell/PDFTagCell.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/TagSearch/TagView.swift
  Presentation/Home/TagSearch/TagViewModel.swift
  Presentation/OriginalPaper/Menus/Comment/CommentCell.swift
  Presentation/OriginalPaper/Menus/Comment/ViewModel/CommentViewModel.swift
  Presentation/OriginalPaper/OriginalView.swift
Labels: Fix, PR-NeedReview

#491 [Fix] 하이라이트 지우기 오류 해결
  Presentation/MainPDF/ViewModel/MainPDFViewModel.swift
  Presentation/OriginalPaper/Menus/Drawing/PDFDrawer.swift
  Presentation/OriginalPaper/OriginalViewController.swift
Labels: Fix, PR-NeedReview

#494 [Fix] 커스텀 알럿 수정
  Data/CoreData/Repositories/PaperDataRepositoryImpl.swift
  DesignSystem/Views/CustomAlert.swift
  Domain/Interfaces/PDFSharedData.swift
  Domain/UseCases/HomeSearchUseCase.swift
  Domain/UseCases/HomeViewUseCase.swift
  Domain/UseCases/TagViewUseCase.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/PaperListView.swift
  Presentation/OriginalPaper/Menus/FigureList/ViewModel/FocusFigureViewModel.swift
Labels: Fix, PR-NeedReview

#497 [Fix] 4.0 QA HomeListView 관련 수정사항 반영
  Data/CoreData/Reazy.xcdatamodeld/Reazy4.0.xcdatamodel/contents
  DesignSystem/Views/CustomAlert.swift
  Domain/UseCases/HomeViewUseCase.swift
  Presentation/Home/HomeListView.swift
  Presentation/Home/HomeSearch/Cell/HomePDFCell.swift
  Presentation/Home/HomeSearch/HomeSearchView.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/ViewModel/HomeViewModel.swift
  Resources/Assets.xcassets/icons/emptydoc.imageset/Contents.json
  Resources/Assets.xcassets/icons/emptydoc.imageset/emptydoc.svg
Labels: Fix, PR-NeedReview

#504 [Fix] 홈 뷰 QA 반영
  DesignSystem/Views/SearchBar.swift
  Presentation/AppView.swift
  Presentation/Home/HomeListView.swift
  Presentation/Home/HomeSearch/ViewModel/HomeSearchViewModel.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/ViewModel/HomeViewModel.swift
  Presentation/MainPDF/MainPDFView.swift
  Presentation/OriginalPaper/Menus/SearchList/Components/SearchListCell.swift
  Presentation/OriginalPaper/Menus/SearchList/SearchView.swift
  Presentation/OriginalPaper/Menus/SearchList/ViewModel/SearchViewModel.swift
  Presentation/OriginalPaper/OriginalViewController.swift
Labels: Fix, PR-NeedReview

#505 [Fix] 태그 관련 QA 수정
  Presentation/Home/HomeSearch/Cell/HomePDFCell.swift
  Presentation/Home/HomeSearch/HomeSearchView.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/PaperListView.swift
  Presentation/Home/TagControl/TagControlView.swift
  Presentation/Home/TagControl/ViewModel/TagControlViewModel.swift
  Presentation/Home/TagSearch/TagView.swift
Labels: Fix, PR-NeedReview

#506 [Fix] 태그 뷰 관련 QA 수정
  Data/Extension/FileManager + Extension.swift
  Domain/Entities/Tag.swift
  Presentation/Home/HomeSearch/Cell/HomePDFCell.swift
  Presentation/Home/HomeSearch/HomeSearchView.swift
  Presentation/Home/PaperListView.swift
  Presentation/Home/SettingView.swift
  Presentation/Home/TagSearch/TagView.swift
  Presentation/Home/TagSearch/TagViewModel.swift
Labels: Fix, PR-NeedReview

#507 [Chore] 앱 버전 업데이트 및 구글 애널리틱스 코드 추가
  Presentation/AppView.swift
  Presentation/OriginalPaper/Menus/Translation/TranslateView.swift
  Reazy.xcodeproj/project.pbxproj
  Reazy.xcodeproj/xcshareddata/xcschemes/Reazy.xcscheme
Labels: Chore, PR-NeedReview

#509 [Fix] Figure 추출 시 무한로딩 에러 해결
  Presentation/OriginalPaper/Menus/FigureList/ViewModel/FocusFigureViewModel.swift
Labels: PR-NeedReview

#503 [Feat] 영어 일본어 다국어 추가
  Localizable.xcstrings
  Presentation/Helper/Date + Extension.swift
  Presentation/Home/HomeListView.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/Paper/PaperListView.swift
  Presentation/Home/PaperListView.swift
  Presentation/MainPDF/PDFInfoMenu.swift
  Presentation/MainPDF/ViewModel/PDFInfoMenuViewModel.swift
  Presentation/OriginalPaper/Menus/Collection/AnnotationCollectionCell.swift
  Reazy.xcodeproj/project.pbxproj
  action-extension/ja.lproj/MainInterface.strings
  share-extension/ja.lproj/MainInterface.strings
Labels: Chore, PR-NeedReview

#512 [Fix] 4.0 HomeView QA 내용 반영
  Data/CoreData/Reazy.xcdatamodeld/Reazy4.0.xcdatamodel/contents
  Domain/Entities/PaperInfo.swift
  Domain/Entities/Tag.swift
  Domain/UseCases/HomeViewUseCase.swift
  Domain/UseCases/TagViewUseCase.swift
  Presentation/Home/HomeFolderPopoverView.swift
  Presentation/Home/HomeListView.swift
  Presentation/Home/HomeSearch/Cell/HomePDFCell.swift
  Presentation/Home/HomeSearch/Cell/PDFTagCell.swift
  Presentation/Home/HomeSearch/HomeSearchView.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/MoveFolderView.swift
  Presentation/Home/PaperListView.swift
  Presentation/Home/TagSearch/TagView.swift
  Presentation/Home/ViewModel/HomeViewModel.swift
Labels: Fix, PR-NeedReview

#514 [Fix] 코멘트 위치에 따른 주석 이미지와 갯수 순서 조정
  Presentation/OriginalPaper/Menus/Comment/ViewModel/CommentViewModel.swift
  Reazy.xcodeproj/project.pbxproj
Labels: Fix, PR-NeedReview

#516 [Fix] V4.0 Tag 관련 QA 반영
  DesignSystem/Views/DynamicCellLayout.swift
  Presentation/Home/HomeSearch/Cell/HomePDFCell.swift
  Presentation/Home/HomeSearch/Cell/PDFTagCell.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/TagControl/TagControlView.swift
  Presentation/Home/TagControl/ViewModel/TagControlViewModel.swift
  Presentation/Home/TagSearch/SelectedTagCell.swift
  Presentation/Home/TagSearch/TagView.swift
  Presentation/Home/TagSearch/TagViewModel.swift
Labels: Fix, PR-NeedReview

#518 [Fix] 홈 뷰 관련 QA
  Presentation/Home/HomeSearch/Cell/HomePDFCell.swift
  Presentation/Home/HomeSearch/HomeSearchView.swift
  Presentation/Home/PaperListView.swift
  Presentation/OriginalPaper/Menus/Comment/ViewModel/CommentViewModel.swift
Labels: Fix, PR-NeedReview

#520 [Feat] 집중 모드 시작 방식 변경
  Data/Network/Repositories/FocusFigureRepositoryImpl.swift
  Domain/Interfaces/Repositories/FocusFigureRepository.swift
  Domain/UseCases/FocusFigureUseCase.swift
  Presentation/ConcentratePaper/ConcentrateViewController.swift
  Presentation/MainPDF/MainPDFView.swift
  Presentation/OriginalPaper/Menus/FigureList/Figure/FigureView.swift
  Presentation/OriginalPaper/Menus/FigureList/ViewModel/FocusFigureViewModel.swift
Labels: Feature, PR-NeedReview

#519 [Fix] 코멘트 관련 QA
  Presentation/OriginalPaper/Menus/Collection/AnnotationCollectionView.swift
  Presentation/OriginalPaper/Menus/Comment/ViewModel/CommentViewModel.swift
Labels: Fix, PR-NeedReview
