Repository DeveloperAcademy-POSTECH/2024-MacC-A05-Chillin, pull requests merged in 2025-03, with the labels that each got.

#470 [Design] 태그뷰 디자인하기
  DesignSystem/Views/CustomAlert.swift
  DesignSystem/Views/DynamicCellLayout.swift
  DesignSystem/Views/EllipsisView.swift
  Domain/Entities/Tag.swift
  Domain/Interfaces/DynamicCell.swift
  Domain/UseCases/TagViewUseCase.swift
  Presentation/Home/HomeSearch/Cell/HomePDFCell.swift
  Presentation/Home/HomeSearch/Cell/PDFTagCell.swift
  Presentation/Home/HomeSearch/HomeSearchView.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/TagSearch/SelectedTagCell.swift
  Presentation/Home/TagSearch/TagView.swift
  Presentation/Home/TagSearch/TagViewModel.swift
  Presentation/Home/TagView.swift
  Reazy.xcodeproj/project.pbxproj
  Resources/Assets.xcassets/icons/tagfill.imageset/Contents.json
  Resources/Assets.xcassets/icons/tagfill.imageset/tagfill.svg
Labels: Design, PR-NeedReview

#482 [Feat] 태그 관리 기능 구현
  Data/CoreData/Repositories/PaperDataRepositoryImpl.swift
  Domain/Interfaces/Repositories/PaperDataRepository.swift
  Domain/UseCases/HomeSearchUseCase.swift
  Domain/UseCases/TagControlUseCase.swift
  Presentation/Home/HomeSearch/Cell/HomePDFCell.swift
  Presentation/Home/HomeSearch/HomeSearchView.swift
  Presentation/Home/HomeSearch/ViewModel/HomeSearchViewModel.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/TagControl/TagControlCell.swift
  Presentation/Home/TagControl/TagControlView.swift
  Presentation/Home/TagControl/ViewModel/TagControlViewModel.swift
  Presentation/Home/ViewModel/HomeViewModel.swift
  Presentation/Home/ViewModel/UserDefault+Keys.swift
  Reazy.xcodeproj/project.pbxproj
Labels: Feature, PR-NeedReview

#484 [Fix] 파일 복제 버그 수정
  Data/CoreData/Repositories/PaperDataRepositoryImpl.swift
  Presentation/Helper/Errors/HomeViewError.swift
  Presentation/Home/Paper/PaperListView.swift
  Presentation/MainPDF/MainPDFView.swift
  Presentation/MainPDF/ViewModel/MainPDFViewModel.swift
  Reazy.xcodeproj/project.pbxproj
Labels: Fix, PR-NeedReview
