Repository DeveloperAcademy-POSTECH/2024-MacC-A05-Chillin, pull requests merged in 2025-01, with the labels that each got.

#424 [Feat] 업데이트 알럿창 구현
  Presentation/AppView.swift
  Presentation/Helper/NotificationCenter + Extension.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/ViewModel/HomeViewModel.swift
  Presentation/OriginalPaper/OriginalViewController.swift
Labels: Feature, PR-NeedReview

#426 [Fix] 코멘트 linecap 수정
  Presentation/OriginalPaper/Menus/Comment/ViewModel/CommentViewModel.swift
Labels: Fix

#421 [Feat] SplitView 사이즈 조정 기능 구현
  Presentation/MainPDF/MainPDFView.swift
  Presentation/OriginalPaper/Floating/FloatingSplitView.swift
  build/XCBuildData/9bc1cec56af5971d4c920b50f657ad63.xcbuilddata/build-request.json
  build/XCBuildData/9bc1cec56af5971d4c920b50f657ad63.xcbuilddata/description.msgpack
  build/XCBuildData/9bc1cec56af5971d4c920b50f657ad63.xcbuilddata/manifest.json
  build/XCBuildData/9bc1cec56af5971d4c920b50f657ad63.xcbuilddata/target-graph.txt
  build/XCBuildData/9bc1cec56af5971d4c920b50f657ad63.xcbuilddata/task-store.msgpack
Labels: Feature, PR-NeedReview

#428 [Fix] editFigure 터치 범위 수정
  Presentation/OriginalPaper/Menus/FigureList/Figure/FigureMenu.swift
Labels: Fix, PR-NeedReview

#429 [Chore] 설정 - 인스타 이미지 변경
  Resources/Assets.xcassets/setting_thumbnail.imageset/Contents.json
  Resources/Assets.xcassets/setting_thumbnail.imageset/setting_image.png
  Resources/Assets.xcassets/setting_thumbnail.imageset/setting_imagex2.png
  Resources/Assets.xcassets/setting_thumbnail.imageset/setting_imagex3.png
  Resources/Assets.xcassets/setting_thumbnail.imageset/settingx1.png
  Resources/Assets.xcassets/setting_thumbnail.imageset/settingx2.png
  Resources/Assets.xcassets/setting_thumbnail.imageset/settingx3.png
Labels: Chore, PR-NeedReview

#433 [Fix] 제스처 오류 해결
  Presentation/OriginalPaper/OriginalViewController.swift
Labels: Fix

#434 [Fix] 툴팁 구글 스칼라 검색 변경
  Presentation/OriginalPaper/OriginalViewController.swift
Labels: Fix, PR-NeedReview

#435 [Chore] FloatingView 최소 크기 수정
  Presentation/OriginalPaper/Floating/FloatingView.swift
  Presentation/OriginalPaper/Floating/FloatingViewModel.swift
  Presentation/OriginalPaper/Floating/FloatingViewsContainer.swift
  Presentation/OriginalPaper/Menus/FigureList/Collection/CollectionView.swift
  Presentation/OriginalPaper/Menus/FigureList/Figure/FigureView.swift
Labels: Chore, PR-NeedReview

#439 [Chore] 버전 업데이트
  Reazy.xcodeproj/project.pbxproj
Labels: Chore, PR-NeedReview

#444 [Chore] 검색 디테일 수정
  Presentation/OriginalPaper/Menus/SearchList/SearchView.swift
  Presentation/OriginalPaper/Menus/SearchList/ViewModel/SearchViewModel.swift
Labels: Chore, PR-NeedReview

#449 [Chore] Floating Split View 최소 크기 및 디자인 오류 수정
  Presentation/MainPDF/MainPDFView.swift
  Presentation/OriginalPaper/Floating/FloatingSplitView.swift
Labels: Chore, Design

#450 [Chore] 공유 시 PDF 필기 포함해서 저장되게 수정
  Presentation/MainPDF/PDFInfoMenu.swift
Labels: Chore, PR-NeedReview

#452 [Feat] 4.0 사이드바 디자인 레이아웃 반영
  Presentation/Home/HomeListView.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/Paper/PaperListView.swift
  Presentation/Home/TagView.swift
  Presentation/Home/ViewModel/HomeViewModel.swift
  Reazy.xcodeproj/project.pbxproj
Labels: Design, PR-NeedReview

#455 [Chore] 업데이트 알림 굵기 통일 및 번역 복사 기능
  Presentation/AppView.swift
  Presentation/Home/HomeView.swift
  Presentation/Home/Paper/PaperInfoView.swift
  Presentation/OriginalPaper/Menus/Translation/TranslateView.swift
  Resources/Assets.xcassets/icons/copyDark.imageset/Contents.json
  Resources/Assets.xcassets/icons/copyDark.imageset/copy.svg
  Resources/Assets.xcassets/icons/copyLight.imageset/Contents.json
  Resources/Assets.xcassets/icons/copyLight.imageset/copy.svg
Labels: Chore
